# IPCC project
descriptive analysis of core data
- [ ] year
- [ ] document types
- [ ] sources
- [ ] publishers
- [ ] authors
- [ ] countries
- [ ] institutions

## data source
This is a very large file, so save locally and get rid of what you don't need like abstract.<br>
- core works table: https://dalu-my.sharepoint.com/personal/ph818849_dal_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fph818849_dal_ca%2FDocuments%2Fqsslab%2Fprojects%2Ftca_wp5%2Fwp5_1_dataset%2FCORE%20WORKS%20TABLES&viewid=579f61a4-ddce-4ba8-8e5d-b903863aaa2d&csf=1&web=1&e=ISMMHd&ovuser=60b81999-0b7f-412d-92a3-e17d8ae9e3e0%2Cnc953095%40dal.ca&OR=Teams-HL&CT=1741006231252&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNTAxMzEwNjAxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&CID=bbe386a1-4013-8000-2eb2-7f3cb950df92&cidOR=SPO&FolderCTID=0x01200054C540E80256E946A57D3039D3B6231F
<br>

In [2]:
# import core works
import pandas as pd
import os
import plotly.express as px

In [12]:
df = pd.read_csv("/Users/poppyriddle/Downloads/tables/works.csv")
df.drop(columns=['abstract'], inplace=True)
df.head(2)

# import core_corks.csv
df_core = pd.read_csv("/Users/poppyriddle/Downloads/tables/core_works.csv")
#df_core.head(2)
# merge inner on core_works.csv
df_merged_core = df_core.merge(df,on='openalex_work_id', how='inner')
print(len(df_merged_core))
df_merged_core.head(2)

6008

                   openalex_work_id                                              title  ...  cited_by_count reference_count
0  https://openalex.org/W2781567654  Declining oxygen in the global ocean and coast...  ...            2609             128
1  https://openalex.org/W2004113883  Are there social limits to adaptation to clima...  ...            2345             106

[2 rows x 8 columns]

In [18]:
pub_year_df = pd.DataFrame(df_merged_core.groupby(df_merged_core['publication_year'])['publication_year'].count()).unstack()

pub_year_df = pub_year_df.reset_index()
pub_year_df.drop(columns=['level_0'], inplace=True)
pub_year_df = pub_year_df.rename(columns={'publication_year':'year',0:'count'})
pub_year_df

    year  count
0   1687      1
1   1921      1
2   1951      1
3   1961      1
4   1968      2
5   1969      1
6   1974      1
7   1976      2
8   1978      1
9   1979      1
10  1980      3
11  1982      1
12  1983      2
13  1984      1
14  1987      2
15  1989      2
16  1990      3
17  1991      3
18  1992      5
19  1993      3
20  1994      4
21  1995      4
22  1996      7
23  1997      3
24  1998      4
25  1999      6
26  2000     10
27  2001     20
28  2002     18
29  2003     25
30  2004     25
31  2005     35
32  2006     47
33  2007     66
34  2008     79
35  2009    107
36  2010    157
37  2011    213
38  2012    311
39  2013    530
40  2014    615
41  2015    838
42  2016    881
43  2017    989
44  2018    754
45  2019    222
46  2022      1

In [41]:

fig = px.bar(pub_year_df,
            x="year",
            y='count',
            title="Core Works by year, 1995-2020",
            template="simple_white",
            labels={ # replaces default labels by column name
                "count": "Count",  "year": "Published year"},)
fig.show()

In [46]:
# doc types on df_merged_core
doc_type_df = pd.DataFrame(df_merged_core.groupby(df_merged_core['type'])['type'].count()).unstack()
doc_type_df = doc_type_df.reset_index()
doc_type_df.drop(columns=['level_0'], inplace=True)
doc_type_df = doc_type_df.rename(columns={'type':'type',0:'count'})
doc_type_df = doc_type_df.sort_values('count', ascending=False)
doc_type_df.to_excel("tables/doc_type.xlsx")
doc_type_df

               type  count
0           article   5441
12           review    258
2      book-chapter    167
1              book     84
11           report     13
6            letter     12
9          preprint     12
7             other     10
4         editorial      3
5           erratum      3
3      dissertation      2
10  reference-entry      2
8          paratext      1

In [47]:
fig = px.bar(doc_type_df,
            x="type",
            y='count',
            title="Count of Document types",
            text_auto=True,
            template="simple_white",
            labels={ # replaces default labels by column name
                "count": "Count",  "type": "Document type"},
            category_orders={ # replaces default order by column name
                "type": ["article","review","book-chapter","book","report","letter","preprint","other","editorial","erratum","dissertation","reference-entry","paratext"]},)
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

In [66]:
# journals source_id	source_name
source_df = pd.DataFrame(df_merged_core.groupby(['source_name'])['source_id'].count()).unstack()

source_df = source_df.reset_index()
source_df.drop(columns=['level_0'], inplace=True)
source_df = source_df.rename(columns={'source_name':'source_name',0:'count'})
source_df = source_df.sort_values('count', ascending=False)
#source_df = source_df.head(10)
#source_df.to_excel("tables/source_names.xlsx")
source_df

                                           source_name  count
332                       Geophysical Research Letters    320
581                              Nature Climate Change    230
435                                 Journal of Climate    154
580                                             Nature    140
340                              Global Change Biology    126
..                                                 ...    ...
392  International Journal of Global Environmental ...      1
394         International Journal of Indigenous Health      1
395            International Journal of Plant Genomics      1
396            International Journal of Plant Sciences      1
859                               Études/Inuit/Studies      1

[860 rows x 2 columns]

In [67]:
# new df /Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_oa_data.csv
core_oa_df = pd.read_csv("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_oa_data.csv", encoding='UTF-8')
core_oa_df.head(5)

                   openalex_work_id  is_oa  ...  oa_status                                             oa_url
0  https://openalex.org/W2781567654   True  ...      green            https://doi.org/10.1126/science.aam7240
1  https://openalex.org/W2004113883  False  ...     closed                                                NaN
2  https://openalex.org/W2013045877  False  ...      green  https://dlc.dlib.indiana.edu/bitstreams/b2064f...
3  https://openalex.org/W2025956066  False  ...     closed                                                NaN
4  https://openalex.org/W4245300726   True  ...     bronze    https://ajs.scholasticahq.com/article/61570.pdf

[5 rows x 5 columns]

In [75]:
# oa status
oa_status_df = pd.DataFrame(core_oa_df.groupby(['oa_status'])['oa_status'].count()).unstack()
oa_status_df = oa_status_df.reset_index()
oa_status_df.drop(columns=['level_0'], inplace=True)
oa_status_df = oa_status_df.rename(columns={'oa_status':'oa_status',0:'Count'})
oa_status_df = oa_status_df.sort_values('Count', ascending=False)
oa_status_df.to_excel("tables/oa_status.xlsx")
oa_status_df

  oa_status  Count
1    closed   2360
3      gold   1167
0    bronze   1091
4     green    761
5    hybrid    688
2   diamond     48

In [78]:
# read rds file using pyreadr package
import pyreadr
result = pyreadr.read_r('/Users/poppyriddle/Downloads/core_works.rds')

# done! let's see what we got
print(result.keys()) # let's check what objects we got

LibrdataError: Invalid file, or file has unsupported features

In [76]:
# countries and affiliations
country_df = pd.read_csv("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_affiliation_data.csv", encoding="UTF-8")
country_df.head(5)

                   openalex_work_id  is_oa  ...  oa_status                                             oa_url
0  https://openalex.org/W2781567654   True  ...      green            https://doi.org/10.1126/science.aam7240
1  https://openalex.org/W2004113883  False  ...     closed                                                NaN
2  https://openalex.org/W2013045877  False  ...      green  https://dlc.dlib.indiana.edu/bitstreams/b2064f...
3  https://openalex.org/W2025956066  False  ...     closed                                                NaN
4  https://openalex.org/W4245300726   True  ...     bronze    https://ajs.scholasticahq.com/article/61570.pdf

[5 rows x 5 columns]