# IPCC project
descriptive analysis of core data
- [ ] year
- [ ] document types
- [ ] sources
- [ ] publishers
- [ ] authors
- [ ] countries
- [ ] institutions

## data source
This is a very large file, so save locally and get rid of what you don't need like abstract.<br>
- core works table: https://dalu-my.sharepoint.com/personal/ph818849_dal_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fph818849_dal_ca%2FDocuments%2Fqsslab%2Fprojects%2Ftca_wp5%2Fwp5_1_dataset%2FCORE%20WORKS%20TABLES&viewid=579f61a4-ddce-4ba8-8e5d-b903863aaa2d&csf=1&web=1&e=ISMMHd&ovuser=60b81999-0b7f-412d-92a3-e17d8ae9e3e0%2Cnc953095%40dal.ca&OR=Teams-HL&CT=1741006231252&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNTAxMzEwNjAxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&CID=bbe386a1-4013-8000-2eb2-7f3cb950df92&cidOR=SPO&FolderCTID=0x01200054C540E80256E946A57D3039D3B6231F
<br>

In [2]:
# import core works
import pandas as pd
import os
import plotly.express as px

In [12]:
df = pd.read_csv("/Users/poppyriddle/Downloads/tables/works.csv")
df.drop(columns=['abstract'], inplace=True)
df.head(2)

# import core_corks.csv
df_core = pd.read_csv("/Users/poppyriddle/Downloads/tables/core_works.csv")
#df_core.head(2)
# merge inner on core_works.csv
df_merged_core = df_core.merge(df,on='openalex_work_id', how='inner')
print(len(df_merged_core))
df_merged_core.head(2)

6008

                   openalex_work_id                                              title  ...  cited_by_count reference_count
0  https://openalex.org/W2781567654  Declining oxygen in the global ocean and coast...  ...            2609             128
1  https://openalex.org/W2004113883  Are there social limits to adaptation to clima...  ...            2345             106

[2 rows x 8 columns]

In [6]:
df_old = df[df['publication_year']==1400]
df_old

                        openalex_work_id                                              title  ...  cited_by_count reference_count
483534  https://openalex.org/W4233014035  Density Estimation for Statistics and Data Ana...  ...            8370               0

[1 rows x 8 columns]

In [24]:
pub_year_df = pd.DataFrame(df.groupby(df['publication_year'])['publication_year'].count()).unstack()

pub_year_df = pub_year_df.reset_index()
pub_year_df.drop(columns=['level_0'], inplace=True)
pub_year_df = pub_year_df.rename(columns={'publication_year':'year',0:'count'})
pub_year_df

     year  count
0    1400      1
1    1500      1
2    1687      1
3    1758      1
4    1761      1
..    ...    ...
187  2021  57343
188  2022  53982
189  2023  52898
190  2024  50019
191  2025  15165

[192 rows x 2 columns]

In [25]:

fig = px.bar(pub_year_df, x="year", y='count', title="Publication type by year")
fig.show()