# IPCC project
descriptive analysis of core data
- [ ] year
- [ ] document types
- [ ] sources
- [ ] publishers
- [ ] authors
- [ ] countries
- [ ] institutions

## data source
This is a very large file, so save locally and get rid of what you don't need like abstract.<br>
- core works table: https://dalu-my.sharepoint.com/personal/ph818849_dal_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fph818849_dal_ca%2FDocuments%2Fqsslab%2Fprojects%2Ftca_wp5%2Fwp5_1_dataset%2FCORE%20WORKS%20TABLES&viewid=579f61a4-ddce-4ba8-8e5d-b903863aaa2d&csf=1&web=1&e=ISMMHd&ovuser=60b81999-0b7f-412d-92a3-e17d8ae9e3e0%2Cnc953095%40dal.ca&OR=Teams-HL&CT=1741006231252&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNTAxMzEwNjAxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&CID=bbe386a1-4013-8000-2eb2-7f3cb950df92&cidOR=SPO&FolderCTID=0x01200054C540E80256E946A57D3039D3B6231F
<br>

In [1]:
# import core works
import pandas as pd
import os
import plotly.express as px

In [2]:
df = pd.read_csv("/Users/poppyriddle/Downloads/tables/works.csv")
df.drop(columns=['abstract'], inplace=True)
df.head(2)

# import core_corks.csv
df_core = pd.read_csv("/Users/poppyriddle/Downloads/tables/core_works.csv")
#df_core.head(2)
# merge inner on core_works.csv
df_merged_core = df_core.merge(df,on='openalex_work_id', how='inner')
print(len(df_merged_core))
df_merged_core.head(2)

6008

                   openalex_work_id  ... reference_count
0  https://openalex.org/W2781567654  ...             128
1  https://openalex.org/W2004113883  ...             106

[2 rows x 8 columns]

In [3]:
pub_year_df = pd.DataFrame(df_merged_core.groupby(df_merged_core['publication_year'])['publication_year'].count()).unstack()

pub_year_df = pub_year_df.reset_index()
pub_year_df.drop(columns=['level_0'], inplace=True)
pub_year_df = pub_year_df.rename(columns={'publication_year':'year',0:'count'})
pub_year_df

    year  count
0   1687      1
1   1921      1
2   1951      1
3   1961      1
4   1968      2
5   1969      1
6   1974      1
7   1976      2
8   1978      1
9   1979      1
10  1980      3
11  1982      1
12  1983      2
13  1984      1
14  1987      2
15  1989      2
16  1990      3
17  1991      3
18  1992      5
19  1993      3
20  1994      4
21  1995      4
22  1996      7
23  1997      3
24  1998      4
25  1999      6
26  2000     10
27  2001     20
28  2002     18
29  2003     25
30  2004     25
31  2005     35
32  2006     47
33  2007     66
34  2008     79
35  2009    107
36  2010    157
37  2011    213
38  2012    311
39  2013    530
40  2014    615
41  2015    838
42  2016    881
43  2017    989
44  2018    754
45  2019    222
46  2022      1

In [4]:

fig = px.bar(pub_year_df,
            x="year",
            y='count',
            title="Core Works by year, 1995-2020",
            template="simple_white",
            labels={ # replaces default labels by column name
                "count": "Count",  "year": "Published year"},)
fig.show()

In [5]:
# doc types on df_merged_core
doc_type_df = pd.DataFrame(df_merged_core.groupby(df_merged_core['type'])['type'].count()).unstack()
doc_type_df = doc_type_df.reset_index()
doc_type_df.drop(columns=['level_0'], inplace=True)
doc_type_df = doc_type_df.rename(columns={'type':'type',0:'count'})
doc_type_df = doc_type_df.sort_values('count', ascending=False)
doc_type_df.to_excel("tables/doc_type.xlsx")
doc_type_df

               type  count
0           article   5441
12           review    258
2      book-chapter    167
1              book     84
11           report     13
6            letter     12
9          preprint     12
7             other     10
4         editorial      3
5           erratum      3
3      dissertation      2
10  reference-entry      2
8          paratext      1

In [6]:
fig = px.bar(doc_type_df,
            x="type",
            y='count',
            title="Count of Document types",
            text_auto=True,
            template="simple_white",
            labels={ # replaces default labels by column name
                "count": "Count",  "type": "Document type"},
            category_orders={ # replaces default order by column name
                "type": ["article","review","book-chapter","book","report","letter","preprint","other","editorial","erratum","dissertation","reference-entry","paratext"]},)
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

In [7]:
# journals source_id	source_name
source_df = pd.DataFrame(df_merged_core.groupby(['source_name'])['source_id'].count()).unstack()

source_df = source_df.reset_index()
source_df.drop(columns=['level_0'], inplace=True)
source_df = source_df.rename(columns={'source_name':'source_name',0:'count'})
source_df = source_df.sort_values('count', ascending=False)
#source_df = source_df.head(10)
#source_df.to_excel("tables/source_names.xlsx")
source_df

                                           source_name  count
332                       Geophysical Research Letters    320
581                              Nature Climate Change    230
435                                 Journal of Climate    154
580                                             Nature    140
340                              Global Change Biology    126
..                                                 ...    ...
392  International Journal of Global Environmental ...      1
394         International Journal of Indigenous Health      1
395            International Journal of Plant Genomics      1
396            International Journal of Plant Sciences      1
859                               Études/Inuit/Studies      1

[860 rows x 2 columns]

In [8]:
# new df /Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_oa_data.csv
core_oa_df = pd.read_csv("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_oa_data.csv", encoding='UTF-8')
core_oa_df.head(5)

                   openalex_work_id  ...                                             oa_url
0  https://openalex.org/W2781567654  ...            https://doi.org/10.1126/science.aam7240
1  https://openalex.org/W2004113883  ...                                                NaN
2  https://openalex.org/W2013045877  ...  https://dlc.dlib.indiana.edu/bitstreams/b2064f...
3  https://openalex.org/W2025956066  ...                                                NaN
4  https://openalex.org/W4245300726  ...    https://ajs.scholasticahq.com/article/61570.pdf

[5 rows x 5 columns]

In [9]:
# oa status
oa_status_df = pd.DataFrame(core_oa_df.groupby(['oa_status'])['oa_status'].count()).unstack()
oa_status_df = oa_status_df.reset_index()
oa_status_df.drop(columns=['level_0'], inplace=True)
oa_status_df = oa_status_df.rename(columns={'oa_status':'oa_status',0:'Count'})
oa_status_df = oa_status_df.sort_values('Count', ascending=False)

# add percentages column
oa_status_df['Percentage'] = oa_status_df['Count'].apply(lambda x: x/(oa_status_df['Count'].sum())*100)

oa_status_df.to_excel("tables/oa_status.xlsx")
oa_status_df

  oa_status  Count  Percentage
1    closed   2360   38.593622
3      gold   1167   19.084219
0    bronze   1091   17.841374
4     green    761   12.444808
5    hybrid    688   11.251022
2   diamond     48    0.784955

In [10]:
# countries and affiliations
country_df = pd.read_csv("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_affiliation_data.csv", encoding="UTF-8")
country_df.head(5)

                   openalex_work_id  ... institution_country_code
0  https://openalex.org/W2781567654  ...                       US
1  https://openalex.org/W2781567654  ...                       US
2  https://openalex.org/W2781567654  ...                       DE
3  https://openalex.org/W2781567654  ...                       BE
4  https://openalex.org/W2781567654  ...                       US

[5 rows x 5 columns]

In [11]:
country_code_df = pd.DataFrame(country_df.groupby(['institution_country_code'])['institution_country_code'].count()).unstack()
country_code_df = country_code_df.reset_index()
country_code_df.drop(columns=["level_0"],inplace=True)
country_code_df = country_code_df.rename(columns={'institution_country_code':'country_code',0:'Count'})
country_code_df.to_excel("tables/country_code.xlsx")
country_code_df

    country_code  Count
0             AD      2
1             AE     11
2             AL      1
3             AR     97
4             AS      2
..           ...    ...
135           VI      6
136           VN     54
137           VU      6
138           WS      2
139           ZA    153

[140 rows x 2 columns]

In [13]:
# Plotly chloropleth
# load ISO-3166 codes
iso_codes_df = pd.read_excel("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/ISO_3166_country_codes.xlsx")
iso_codes_df = iso_codes_df[['A2_code','A3_code','ISO 3166']]
iso_codes_df

country_code_df_merged = country_code_df.merge(iso_codes_df, left_on='country_code', right_on='A2_code', how='inner')
country_code_df_merged.drop(columns=['A2_code'],inplace=True)
country_code_df_merged

    country_code  Count A3_code                      ISO 3166
0             AD      2     AND                       Andorra
1             AE     11     ARE    United Arab Emirates (the)
2             AL      1     ALB                       Albania
3             AR     97     ARG                     Argentina
4             AS      2     ASM                American Samoa
..           ...    ...     ...                           ...
135           VI      6     VIR  Virgin Islands (U.S.) [ am ]
136           VN     54     VNM               Viet Nam [ ak ]
137           VU      6     VUT                       Vanuatu
138           WS      2     WSM                         Samoa
139           ZA    153     ZAF                  South Africa

[140 rows x 4 columns]

In [14]:
country_code_merged_export = country_code_df_merged.sort_values('Count', ascending=False)
country_code_merged_export.to_excel("tables/country_codes_export.xlsx")
country_code_merged_export

    country_code  ...                                           ISO 3166
131           US  ...                     United States of America (the)
43            GB  ...  United Kingdom of Great Britain and Northern I...
6             AU  ...                                    Australia [ f ]
20            CA  ...                                             Canada
30            DE  ...                                            Germany
..           ...  ...                                                ...
80            MM  ...                                      Myanmar [ x ]
113           SB  ...                                    Solomon Islands
82            MR  ...                                         Mauritania
90            NE  ...                                        Niger (the)
123           TJ  ...                                         Tajikistan

[140 rows x 4 columns]

In [106]:
#plotly chloropleth with country_code_df_merged
import plotly.express as px

fig = px.choropleth(country_code_df_merged,
                    locations="A3_code",
                    color="Count", 
                    hover_name="ISO 3166",
                    locationmode='ISO-3',
                    title="Authors on works by country code associated with institutional affiliation",
                    color_continuous_scale=px.colors.sequential.Plotly3)
fig.show()

In [115]:
# top affiliations 
institution_df = pd.read_csv("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/core_affiliation_data.csv", encoding="UTF-8")
institution_df.head(5)
top_inst_df = pd.DataFrame(institution_df.groupby(['institution_display_name'])['institution_display_name'].count()).unstack()
top_inst_df = top_inst_df.reset_index()
top_inst_df.drop(columns=['level_0'], inplace=True)
top_inst_df = top_inst_df.rename(columns={'institution_display_name':'Affiliation',0:'Count'})
top_inst_df = top_inst_df.sort_values('Count', ascending=False)
top_inst_df.head(10).to_excel("tables/top_inst.xlsx")
top_inst_df

                                            Affiliation  Count
2335                     University of Alaska Fairbanks    472
65    Alfred-Wegener-Institut Helmholtz-Zentrum für ...    415
2744                                 Utrecht University    304
1533                       National Oceanography Centre    295
224                            British Antarctic Survey    292
...                                                 ...    ...
1369  Ministry of Environment, Forests and Climate C...      1
1368                 Ministry of Environment and Energy      1
1364     Ministry of Agriculture Forestry and Fisheries      1
1363                        Ministerio de Salud Pública      1
2901            Štátne Lesy Tatranského Národního Parku      1

[2902 rows x 2 columns]

In [124]:
institution_df
institution_df.fillna(value=0, inplace=True)
inst_has_nan = institution_df[institution_df['institution_id']==0]
print(f"Length of df with 0 in institution_id: {len(inst_has_nan)}")
print(f"Length of author list: {len(institution_df)}")
inst_has_nan

Length of df with 0 in institution_id: 2291
Length of author list: 34344

                       openalex_work_id  ... institution_country_code
27     https://openalex.org/W2004113883  ...                        0
76     https://openalex.org/W2032266442  ...                        0
77     https://openalex.org/W2032266442  ...                        0
96     https://openalex.org/W1548516473  ...                        0
97     https://openalex.org/W1548516473  ...                        0
...                                 ...  ...                      ...
34339  https://openalex.org/W4240253038  ...                        0
34340  https://openalex.org/W4240253038  ...                        0
34341  https://openalex.org/W4240253038  ...                        0
34342  https://openalex.org/W4240253038  ...                        0
34343  https://openalex.org/W4240253038  ...                        0

[2291 rows x 5 columns]

## import cluster 2 excel spreadsheet

In [10]:
cluster2_df

     cluster_louvain                sdg
0                  2  Quality education
1                  2     Climate action
2                  2     Climate action
3                  2        Zero hunger
4                  2       Life on land
..               ...                ...
511                2     Climate action
512                2                NaN
513                2     Climate action
514                2     Climate action
515                2   Life below water

[516 rows x 2 columns]

In [18]:
cluster2_df = pd.read_excel("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/descriptive_analysis/data/cluster_2.xlsx")
cluster2_df
sdg_count = pd.DataFrame(cluster2_df.groupby(['sdg'])['sdg'].count()).unstack()
sdg_count = sdg_count.reset_index()
sdg_count = sdg_count.drop(columns=['level_0'])
sdg_count = sdg_count.rename(columns={'sdg':'SDG',0:'Count'})
sdg_count = sdg_count.sort_values('Count', ascending=False)
sdg_count['Percentage'] = sdg_count['Count'].apply(lambda x:x/(sum(sdg_count['Count']))*100)
sdg_count.to_excel("tables/sdgs_cluster2.xlsx")
sdg_count

                                        SDG  Count  Percentage
1                            Climate action    199   50.379747
4                          Life below water     64   16.202532
0                Clean water and sanitation     44   11.139241
5                              Life on land     35    8.860759
2           Decent work and economic growth     12    3.037975
3   Industry, innovation and infrastructure     12    3.037975
9        Sustainable cities and communities     12    3.037975
10                              Zero hunger     11    2.784810
6                                No poverty      3    0.759494
8    Responsible consumption and production      2    0.506329
7                         Quality education      1    0.253165

In [17]:
fig = px.bar(sdg_count,
            x="Count",
            y='SDG',
            title="Proportion of SDGs within Cluster 2",
            text_auto=True,
            template="simple_white",
            #labels={"count": "Count",  "type": "Document type"},
            )
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.show()

# CWTS clusters

In [15]:
#import cwts tables
cwts_df = pd.read_csv("/Users/poppyriddle/Documents/TCA/IPCC report/clustered_works.csv", encoding="UTF-8")
cwts_df.head(5)

                   openalex_work_id  ... in_core_cluster
0  https://openalex.org/W1000309748  ...           False
1  https://openalex.org/W1000394224  ...            True
2  https://openalex.org/W1000416519  ...            True
3  https://openalex.org/W1000459970  ...            True
4  https://openalex.org/W1000574356  ...            True

[5 rows x 12 columns]

In [26]:
micro_id_df = pd.read_csv("/Users/poppyriddle/Documents/TCA/IPCC report/micro_cluster_keyword.tsv",sep="\t",encoding_errors='ignore', encoding="iso-8859-1")
micro_id_df.head(20)

    micro_cluster_id  keyword_seq                            keyword
0                  1            1                             Zircon
1                  1            2                      Geochronology
2                  1            3                          Tectonics
3                  1            4                     Granitic Rocks
4                  1            5               Isotopic Composition
5                  1            6                   Subduction Zones
6                  1            7                   Mantle Evolution
7                  1            8                    Plate Tectonics
8                  1            9             Thermodynamic Modeling
9                  1           10                 Continental Growth
10                 2            1          Density Functional Theory
11                 2            2              Dispersion Correction
12                 2            3          Ab Initio Parametrization
13                 2            4              Wavefunction Analyzer
14                 2            5              Semiempirical Methods
15                 2            6         Van der Waals Interactions
16                 2            7         Continuum Solvation Models
17                 2            8         Hybrid Density Functionals
18                 2            9              Molecular Simulations
19                 2           10  Electronic Structure Calculations